export default function HeadLayout() {
  return (
    <>
      <title>Warung Jujugan</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo/jujugan2.ico" />
      <link rel="preload" href="/images/menu/Ayam Bakar Jumbo.png" as="image" />
      <link rel="preload" href="/images/menu/Ayam Bakar.jpg" as="image" />
      <link rel="preload" href="/images/menu/Juice Alpukat.png" as="image" />
      <link rel="preload" href="/images/menu/Juice Buah Naga.jpeg" as="image" />
      <link rel="preload" href="/images/menu/Juice Jambu.png" as="image" />
      <link rel="preload" href="/images/menu/Juice Nanas.jpeg" as="image" />
      <link rel="preload" href="/images/menu/Mie Ayam.png" as="image" />
      <link rel="preload" href="/images/menu/Mie Ayam Ceker.jpeg" as="image" />
      <link rel="preload" href="/images/menu/Mie Ayam Telur.jpeg" as="image" />
      <link rel="preload" href="/images/menu/Mie Ayam Bakso.jpeg" as="image" />
      <link rel="preload" href="/images/menu/Soto.png" as="image" />
    </>
  );
}
